services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    command: ["serve"]
    
  backend:
    build:
      context: ./giftfinder-backend
      dockerfile: Dockerfile
    container_name: giftfinder-backend
    environment:
      SCRAPER_BASE_URL: http://scraper:8001
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - scraper
      - postgres
    ports:
      - "${BACKEND_PORT}:8080"

  scraper:
    build:
      context: ./giftfinder-scraper
      dockerfile: Dockerfile
    container_name: giftfinder-scraper
    environment:
      OLLAMA_HOST: http://ollama:11434
    restart: always
    depends_on:
      - ollama
    ports:
      - "${SCRAPER_PORT}:8001"

  postgres:
    image: postgres:15
    container_name: giftfinder-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data:
  ollama_models:
