server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/giftfinder
    username: giftfinder
    password: giftfinder
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o-mini

# Para que el front en 5173 pueda pegarle
cors:
  allowed-origins: "http://localhost:5173"

jwt:
  secret: super-secret-key
  expiration-ms: 86400000

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG

scraper:
  base-url: ${SCRAPER_BASE_URL:http://localhost:8001}